# Exercises Lesson 6 

Name: Carlos Cocha

In [9]:
import pandas as pd
import numpy as np

### 1. Read the different files with Cyprus towns temperatures provided in the TData folder and build a dataframe combining all the information. The columns should be the  year and months and you can distinguish between data for the different towns adding an extra column with the town name. Hint: the function concat can be very useful in this case.

In [302]:
months = ["Jan", "Feb", "Mar", "Apr","May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
years  = np.arange(1961, 2096+1, 1)
lis_y  = list(np.array([[years[i]]*12 for i in range(len(years))]).ravel())

In [304]:
tdata_Agrinio = pd.read_csv("./TData/T_Agrinio_EM.csv", index_col=0, names = months, skiprows=1)
tdata_Ajjacio = pd.read_csv("./TData/T_Ajjacio_EM.csv", index_col=0, names = months, skiprows=1)
tdata_Alexandroupolis = pd.read_csv("./TData/T_Alexandroupolis_EM.csv", index_col=0, names = months, skiprows=1)
tdata_Alicante = pd.read_csv("./TData/T_Alicante_EM.csv", index_col=0, names = months, skiprows=1)
tdata_Antalya = pd.read_csv("./TData/T_Antalya_EM.csv", index_col=0, names = months, skiprows=1)
tdata_Araxos = pd.read_csv("./TData/T_Araxos_EM.csv", index_col=0, names = months , skiprows=1)

In [505]:
dframe_Agrinio = pd.DataFrame([tdata_Agrinio.values.ravel()], columns=[lis_y,months*136])
dframe_Ajjacio = pd.DataFrame([tdata_Ajjacio.values.ravel()], columns=[lis_y,months*136])
dframe_Alexandroupolis = pd.DataFrame([tdata_Alexandroupolis.values.ravel()], columns=[lis_y,months*136])
dframe_Alicante = pd.DataFrame([tdata_Alicante.values.ravel()], columns=[lis_y,months*136])
dframe_Antalya = pd.DataFrame([tdata_Antalya.values.ravel()], columns=[lis_y,months*136])
dframe_Araxos = pd.DataFrame([tdata_Araxos.values.ravel()], columns=[lis_y,months*136])

In [506]:
concat = pd.concat([dframe_Agrinio, dframe_Ajjacio, dframe_Alexandroupolis,dframe_Alicante,
                    dframe_Antalya,dframe_Araxos])
concat.index = ["Agrinio","Ajjacio", "Alexandroupolis", "Alicante", "Antalya", "Araxos" ]
concat.index.names = ["Towns"]
concat

1961                                                   \
                   Jan    Feb    Mar    Apr    May    Jun    Jul    Aug   
Towns                                                                     
Agrinio           8.56   9.18  10.86  14.62  18.13  21.98  25.97  25.33   
Ajjacio           9.42   9.85  10.68  12.63  15.97  19.59  23.13  23.50   
Alexandroupolis   5.41   6.40   8.75  13.61  17.28  21.87  25.97  24.51   
Alicante         11.55  11.65  13.30  15.33  17.58  20.88  24.54  25.10   
Antalya           9.63  10.15  12.24  17.23  20.34  24.64  27.94  27.62   
Araxos           10.32  10.45  11.87  14.96  18.25  21.78  25.56  25.32   

                               ...   2096                                     \
                   Sep    Oct  ...    Mar    Apr    May    Jun    Jul    Aug   
Towns                          ...                                             
Agrinio          21.75  17.61  ...  13.87  16.73  21.76  25.84  30.33  30.60   
Ajjacio          20.07  15.80  ...  13.43  15.01  18.34  21.76  26.52  27.55   
Alexandroupolis  20.25  14.78  ...  11.82  15.65  21.82  26.13  30.31  29.63   
Alicante         22.11  17.67  ...  16.24  17.83  21.01  23.79  27.58  28.62   
Antalya          24.57  20.18  ...  15.89  19.36  24.48  29.08  31.86  32.28   
Araxos           22.32  18.70  ...  14.78  17.21  21.25  25.30  29.47  30.16   

                                             
                   Sep    Oct    Nov    Dec  
Towns                                        
Agrinio          26.37  22.40  16.62  11.99  
Ajjacio          24.24  19.56  15.42  12.85  
Alexandroupolis  24.43  19.55  13.62 -14.64  
Alicante         25.91  20.58  16.80  14.22  
Antalya          28.84  25.50  19.19  13.82  
Araxos           26.73  23.24  18.09  13.70  

[6 rows x 1632 columns]

### 2. A different way to combine the Cyprus towns temperature data provided in the TData folder is to build a dataframe whose index is a hierarchical one, with the year and month and there are as many columns as towns, labeled with the town names. Hint: The concat and unstack functions can be helpful in this case. 

In [354]:
conc = pd.concat([tdata_Agrinio.stack(), tdata_Ajjacio.stack(), tdata_Alexandroupolis.stack(),tdata_Alicante.stack(), tdata_Antalya.stack(), tdata_Agrinio.stack()],
                 axis=1, keys = ["Agrinio", "Ajjacio","Alexandroupolis","Alicante","Antalya","Agrinio"])
dframe2= pd.DataFrame(conc)
dframe2.index.names = ["Years", "Month"]
dframe2

Agrinio  Ajjacio  Alexandroupolis  Alicante  Antalya  Agrinio
Years Month                                                               
1961  Jan       8.56     9.42             5.41     11.55     9.63     8.56
      Feb       9.18     9.85             6.40     11.65    10.15     9.18
      Mar      10.86    10.68             8.75     13.30    12.24    10.86
      Apr      14.62    12.63            13.61     15.33    17.23    14.62
      May      18.13    15.97            17.28     17.58    20.34    18.13
...              ...      ...              ...       ...      ...      ...
2096  Aug      30.60    27.55            29.63     28.62    32.28    30.60
      Sep      26.37    24.24            24.43     25.91    28.84    26.37
      Oct      22.40    19.56            19.55     20.58    25.50    22.40
      Nov      16.62    15.42            13.62     16.80    19.19    16.62
      Dec      11.99    12.85           -14.64     14.22    13.82    11.99

[1632 rows x 6 columns]

### 3. Compute the correlation matrix between the temperatures in the provided Cyprus cities from the previous exercise dataframe.

In [361]:
print(dframe2.corr().values)

[[1.         0.99230825 0.99193741 0.99274733 0.99725476 1.        ]
 [0.99230825 1.         0.97514453 0.99507906 0.98790939 0.99230825]
 [0.99193741 0.97514453 1.         0.98041857 0.98992406 0.99193741]
 [0.99274733 0.99507906 0.98041857 1.         0.99166574 0.99274733]
 [0.99725476 0.98790939 0.98992406 0.99166574 1.         0.99725476]
 [1.         0.99230825 0.99193741 0.99274733 0.99725476 1.        ]]


### 4. We provide as  an example data set the file meteodat.csv with an excerpt of data with a 10 minute frequency from an automated meteorological station with a span of two months (Jan and Feb 2014). Data are comma separated and you can read them using pd.read_csv. The first column is the date and the second the time.  Transform this data into a dataframe with an index of datetime.

In [465]:
tdata_meteodat = pd.read_csv("./meteodat.csv")
headers = list(tdata_meteodat.columns.values)[2:]
date = tdata_meteodat.values[0:,0].ravel()
time = tdata_meteodat.values[0:,1].ravel()
datetime = [date[i]+ str(" ")+time[i] for i in range(len(time))]
array = tdata_meteodat.values[0:,2:]

In [469]:
dframe_meteodat = pd.DataFrame(array, columns = headers,  index= datetime)
dframe_meteodat.index = pd.to_datetime(dframe_meteodat.index)
dframe_meteodat.index.names = ["Date-Time"]
dframe_meteodat

Tout  Tmax  Tmin H out Dew point Wind Speed  \
Date-Time                                                          
2014-01-01 00:10:00  15.1  15.1  15.1    85      12.6        9.7   
2014-01-01 00:20:00  15.1  15.1  15.1    85      12.6          8   
2014-01-01 00:30:00  15.1  15.1  15.1    86      12.7          8   
2014-01-01 00:40:00  14.9  15.1  14.9    86      12.6          8   
2014-01-01 00:50:00  14.9  14.9  14.8    88      12.9        6.4   
...                   ...   ...   ...   ...       ...        ...   
2014-02-28 23:10:00  13.7  13.8  13.7    83      10.8        9.7   
2014-02-28 23:20:00  13.6  13.7  13.6    83      10.8          8   
2014-02-28 23:30:00  13.6  13.6  13.6    83      10.7        9.7   
2014-02-28 23:40:00  13.5  13.6  13.5    83      10.7        9.7   
2014-02-28 23:50:00  13.4  13.5  13.4    83      10.6        6.4   

                    Wind Direction Wind Speed Hi Wind Direction Hi Wind Chill  \
Date-Time                                                                       
2014-01-01 00:10:00            SSW          17.7                SW       14.7   
2014-01-01 00:20:00            SSW          14.5               SSW       14.9   
2014-01-01 00:30:00            SSW          16.1                SW       14.9   
2014-01-01 00:40:00            SSW          14.5               SSW       14.8   
2014-01-01 00:50:00            SSW          12.9               SSW       14.9   
...                            ...           ...               ...        ...   
2014-02-28 23:10:00            WNW          20.9                 W       13.1   
2014-02-28 23:20:00            WNW          20.9                 W       13.3   
2014-02-28 23:30:00            WNW          22.5               WNW       12.9   
2014-02-28 23:40:00            WNW          20.9               WNW       12.9   
2014-02-28 23:50:00            WNW          19.3               WNW       13.3   

                    Heat Index THM Index Pressure Rain Rain Max   Tin H in  \
Date-Time                                                                    
2014-01-01 00:10:00       15.1      14.7     1023    0        0  16.4   56   
2014-01-01 00:20:00       15.1      14.9   1022.9    0        0  16.6   56   
2014-01-01 00:30:00       15.1      14.9   1022.8    0        0  16.6   56   
2014-01-01 00:40:00       14.9      14.8   1022.7    0        0  16.6   56   
2014-01-01 00:50:00       14.9      14.9   1022.6    0        0  16.6   56   
...                        ...       ...      ...  ...      ...   ...  ...   
2014-02-28 23:10:00       13.6      12.9     1025    0        0  19.8   59   
2014-02-28 23:20:00       13.5      13.2   1024.9    0        0  19.8   59   
2014-02-28 23:30:00       13.4      12.8   1024.7    0        0  19.8   59   
2014-02-28 23:40:00       13.4      12.8   1024.5    0        0  19.8   59   
2014-02-28 23:50:00       13.3      13.2   1024.5    0        0  19.8   59   

                    Dew Point In Heat Index In  
Date-Time                                       
2014-01-01 00:10:00          7.6          15.6  
2014-01-01 00:20:00          7.7          15.7  
2014-01-01 00:30:00          7.7          15.7  
2014-01-01 00:40:00          7.7          15.7  
2014-01-01 00:50:00          7.7          15.7  
...                          ...           ...  
2014-02-28 23:10:00         11.6          19.6  
2014-02-28 23:20:00         11.6          19.6  
2014-02-28 23:30:00         11.6          19.6  
2014-02-28 23:40:00         11.6          19.6  
2014-02-28 23:50:00         11.6          19.6  

[8495 rows x 19 columns]

###  Compute dataframes with downsampling to hourly and daily average values for temperature (Tout), pressure (Pressure), relative humidity (H out), wind speed (Wind Speed), and dew point temperature (Dew point); 

In [476]:
new_meteodat = dframe_meteodat[['Tout','Pressure','H out', 'Wind Speed','Dew point']]
new_meteodat_hourly = new_meteodat.resample("1H").sum()
new_meteodat_hourly

Tout  Pressure  H out  Wind Speed  Dew point
Date-Time                                                        
2014-01-01 00:00:00  75.1    5114.0    430        40.1       63.4
2014-01-01 01:00:00  88.8    6132.9    533        35.2       77.9
2014-01-01 02:00:00  85.6    6129.7    557        27.2       78.7
2014-01-01 03:00:00  86.7    6127.6    565        25.6       81.1
2014-01-01 04:00:00  87.3    6126.9    569        38.5       82.5
...                   ...       ...    ...         ...        ...
2014-12-02 19:00:00  90.7    6128.6    564        66.2       84.7
2014-12-02 20:00:00  90.6    6133.6    573        63.0       86.2
2014-12-02 21:00:00  89.0    6136.2    575        43.2       85.1
2014-12-02 22:00:00  89.1    6137.9    576        44.8       85.5
2014-12-02 23:00:00  89.9    6138.3    576        51.4       86.0

[8064 rows x 5 columns]

In [477]:
new_meteodat_daily = new_meteodat.resample("24H").sum()
new_meteodat_daily

Tout  Pressure  H out  Wind Speed  Dew point
Date-Time                                                 
2014-01-01  2058.0  145933.4  13139       524.0     1870.1
2014-01-02  1906.1  146492.6  11283      1181.5     1343.6
2014-01-03     0.0       0.0      0         0.0        0.0
2014-01-04     0.0       0.0      0         0.0        0.0
2014-01-05     0.0       0.0      0         0.0        0.0
...            ...       ...    ...         ...        ...
2014-11-28     0.0       0.0      0         0.0        0.0
2014-11-29     0.0       0.0      0         0.0        0.0
2014-11-30     0.0       0.0      0         0.0        0.0
2014-12-01  2110.8  147392.5  13613       376.2     1983.4
2014-12-02  1953.4  147053.6  13683       673.1     1839.2

[336 rows x 5 columns]

### Sum of rainfall (Rain)

In [494]:
rain_meteodat = dframe_meteodat[['Rain']]
rain_meteodat_hourly = rain_meteodat.resample("1H").sum()
rain_meteodat_hourly

Rain
Date-Time                
2014-01-01 00:00:00   0.0
2014-01-01 01:00:00   0.4
2014-01-01 02:00:00   0.4
2014-01-01 03:00:00   0.2
2014-01-01 04:00:00   0.2
...                   ...
2014-12-02 19:00:00   0.0
2014-12-02 20:00:00   0.0
2014-12-02 21:00:00   0.0
2014-12-02 22:00:00   0.0
2014-12-02 23:00:00   0.0

[8064 rows x 1 columns]

In [496]:
rain_meteodat_daily = rain_meteodat.resample("1H").sum()
rain_meteodat_daily

Rain
Date-Time                
2014-01-01 00:00:00   0.0
2014-01-01 01:00:00   0.4
2014-01-01 02:00:00   0.4
2014-01-01 03:00:00   0.2
2014-01-01 04:00:00   0.2
...                   ...
2014-12-02 19:00:00   0.0
2014-12-02 20:00:00   0.0
2014-12-02 21:00:00   0.0
2014-12-02 22:00:00   0.0
2014-12-02 23:00:00   0.0

[8064 rows x 1 columns]

In [491]:
rain_meteodat_sum = rain_meteodat.sum()
rain_meteodat_sum


Rain    92.4
dtype: float64

### Maximum and minimum values of temperature (Tmax and Tmin) and show the correlation between these variables at hourly and daily scales.

In [498]:
T_meteodat = dframe_meteodat[['Tmax','Tmin']]
T_meteodat_hourly = T_meteodat.resample("1H").sum()
T_meteodat_hourly

Tmax  Tmin
Date-Time                      
2014-01-01 00:00:00  75.3  75.0
2014-01-01 01:00:00  89.3  88.6
2014-01-01 02:00:00  86.0  85.5
2014-01-01 03:00:00  87.0  86.3
2014-01-01 04:00:00  87.5  87.0
...                   ...   ...
2014-12-02 19:00:00  90.9  90.6
2014-12-02 20:00:00  90.6  90.5
2014-12-02 21:00:00  89.6  88.9
2014-12-02 22:00:00  89.2  89.0
2014-12-02 23:00:00  89.9  89.6

[8064 rows x 2 columns]

In [500]:
print(T_meteodat_hourly.corr().values)

[[1.         0.99996171]
 [0.99996171 1.        ]]


In [499]:
T_meteodat_daily = T_meteodat.resample("24H").sum()
T_meteodat_daily

Tmax    Tmin
Date-Time                 
2014-01-01  2066.4  2050.4
2014-01-02  1918.1  1900.2
2014-01-03     0.0     0.0
2014-01-04     0.0     0.0
2014-01-05     0.0     0.0
...            ...     ...
2014-11-28     0.0     0.0
2014-11-29     0.0     0.0
2014-11-30     0.0     0.0
2014-12-01  2117.0  2103.2
2014-12-02  1960.1  1944.4

[336 rows x 2 columns]

In [507]:
print(T_meteodat_daily.corr().values)

[[1.         0.99998994]
 [0.99998994 1.        ]]
